# Generated by Django 5.2 on 2025-04-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0002_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="pic_path",
        ),
        migrations.AlterField(
            model_name="book",
            name="picture",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
