# Generated by Django 5.1.5 on 2025-04-24 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0003_shoppingcart_cartitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="quantitiy",
            new_name="quantity",
        ),
    ]
