# Generated by Django 5.2 on 2025-04-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0003_remove_book_pic_path_alter_book_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="picture",
            field=models.FileField(upload_to="static/uploads/"),
        ),
    ]
