# Generated by Django 5.2 on 2025-04-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0006_alter_book_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="picture",
            field=models.FileField(upload_to="uploads"),
        ),
        migrations.AlterField(
            model_name="book",
            name="publishdate",
            field=models.DateField(auto_now_add=True),
        ),
    ]
